/**
 * Supabase Database Types for Bomberman Online
 *
 * This file will be auto-generated by running:
 * npm run db:generate
 *
 * These manual types match the schema defined in migrations/001_initial_schema.sql
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ============================================================================
// ENUM TYPES
// ============================================================================

export type GameStatus = 'waiting' | 'countdown' | 'playing' | 'intermission' | 'finished' | 'cancelled';
export type GameType = 'casual' | 'ranked' | 'custom' | 'tournament' | 'private';
export type RankTier = 'bronze' | 'silver' | 'gold' | 'platinum' | 'diamond' | 'master' | 'grandmaster';
export type AchievementRarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
export type AchievementCategory = 'combat' | 'survival' | 'social' | 'progression' | 'special' | 'seasonal' | 'secret';
export type TournamentStatus = 'draft' | 'registration' | 'check_in' | 'active' | 'finished' | 'cancelled';
export type TournamentFormat = 'single_elimination' | 'double_elimination' | 'round_robin' | 'swiss';
export type TournamentParticipantStatus = 'registered' | 'checked_in' | 'active' | 'eliminated' | 'winner' | 'disqualified' | 'no_show';
export type FriendshipStatus = 'pending' | 'accepted' | 'blocked' | 'declined';
export type ChatMessageType = 'text' | 'emoji' | 'system' | 'quick_chat';
export type ConnectionStatus = 'connected' | 'disconnected' | 'reconnecting';
export type NotificationType =
  | 'friend_request'
  | 'friend_accepted'
  | 'game_invite'
  | 'tournament_invite'
  | 'tournament_starting'
  | 'tournament_match_ready'
  | 'achievement_unlocked'
  | 'rank_changed'
  | 'system_message';
export type ReportReason = 'cheating' | 'harassment' | 'inappropriate_name' | 'griefing' | 'other';
export type ReportStatus = 'pending' | 'reviewed' | 'action_taken' | 'dismissed';
export type MatchmakingStatus = 'searching' | 'matching' | 'found' | 'cancelled';

// ============================================================================
// JSON COLUMN TYPES
// ============================================================================

export interface GameSettings {
  maxPlayers: number;
  roundTime: number;
  roundsToWin: number;
  suddenDeathTime: number;
  powerupSpawnRate: number;
  allowSpectators: boolean;
  isPrivate?: boolean;
  startingBombs?: number;
  startingRadius?: number;
  startingSpeed?: number;
}

export interface MapTileData {
  tiles: number[][];
  version?: number;
}

export interface SpawnPoint {
  x: number;
  y: number;
}

export interface PowerupDistribution {
  bomb?: number;
  fire?: number;
  speed?: number;
  kick?: number;
  punch?: number;
  skull?: number;
}

export interface AchievementCriteria {
  type: 'kills' | 'wins' | 'games' | 'win_streak' | 'elo' | 'rank' | 'custom';
  target: number | string;
  conditions?: Record<string, unknown>;
}

export interface TournamentPrizePool {
  '1st'?: string;
  '2nd'?: string;
  '3rd'?: string;
  [key: string]: string | undefined;
}

export interface TournamentBracket {
  rounds: TournamentMatch[][];
}

export interface TournamentMatch {
  id: number;
  round: number;
  player1_id?: string;
  player2_id?: string;
  winner_id?: string;
  status: 'pending' | 'ready' | 'in_progress' | 'completed' | 'bye';
  game_id?: string;
  score?: { player1: number; player2: number };
}

export interface ReplayHighlight {
  tick: number;
  type: 'kill' | 'multikill' | 'clutch' | 'close_call';
  description: string;
}

export interface PlayerSettings {
  sfxVolume?: number;
  musicVolume?: number;
  showPlayerNames?: boolean;
  showPing?: boolean;
  colorblindMode?: boolean;
}

// ============================================================================
// DATABASE TABLE TYPES
// ============================================================================

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          clerk_id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          country_code: string | null;
          elo_rating: number;
          peak_elo: number;
          rank_tier: RankTier;
          total_wins: number;
          total_losses: number;
          total_games: number;
          total_kills: number;
          total_deaths: number;
          total_bombs_placed: number;
          total_powerups_collected: number;
          total_playtime_seconds: number;
          current_win_streak: number;
          best_win_streak: number;
          preferred_color: number;
          settings: PlayerSettings;
          is_online: boolean;
          last_seen_at: string;
          is_banned: boolean;
          ban_reason: string | null;
          ban_expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clerk_id: string;
          username: string;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          country_code?: string | null;
          elo_rating?: number;
          peak_elo?: number;
          rank_tier?: RankTier;
          total_wins?: number;
          total_losses?: number;
          total_games?: number;
          total_kills?: number;
          total_deaths?: number;
          total_bombs_placed?: number;
          total_powerups_collected?: number;
          total_playtime_seconds?: number;
          current_win_streak?: number;
          best_win_streak?: number;
          preferred_color?: number;
          settings?: PlayerSettings;
          is_online?: boolean;
          last_seen_at?: string;
          is_banned?: boolean;
        };
        Update: {
          username?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          country_code?: string | null;
          elo_rating?: number;
          peak_elo?: number;
          rank_tier?: RankTier;
          total_wins?: number;
          total_losses?: number;
          total_games?: number;
          total_kills?: number;
          total_deaths?: number;
          total_bombs_placed?: number;
          total_powerups_collected?: number;
          total_playtime_seconds?: number;
          current_win_streak?: number;
          best_win_streak?: number;
          preferred_color?: number;
          settings?: PlayerSettings;
          is_online?: boolean;
          last_seen_at?: string;
          is_banned?: boolean;
          ban_reason?: string | null;
          ban_expires_at?: string | null;
        };
      };
      maps: {
        Row: {
          id: string;
          creator_id: string | null;
          name: string;
          description: string | null;
          thumbnail_url: string | null;
          width: number;
          height: number;
          tiles: MapTileData;
          spawn_points: SpawnPoint[];
          powerup_distribution: PowerupDistribution;
          is_official: boolean;
          is_published: boolean;
          is_featured: boolean;
          play_count: number;
          likes: number;
          dislikes: number;
          average_rating: number;
          version: number;
          parent_map_id: string | null;
          created_at: string;
          updated_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          creator_id?: string | null;
          name: string;
          description?: string | null;
          thumbnail_url?: string | null;
          width?: number;
          height?: number;
          tiles: MapTileData;
          spawn_points: SpawnPoint[];
          powerup_distribution?: PowerupDistribution;
          is_official?: boolean;
          is_published?: boolean;
          is_featured?: boolean;
          play_count?: number;
          likes?: number;
          version?: number;
          parent_map_id?: string | null;
        };
        Update: {
          name?: string;
          description?: string | null;
          thumbnail_url?: string | null;
          width?: number;
          height?: number;
          tiles?: MapTileData;
          spawn_points?: SpawnPoint[];
          powerup_distribution?: PowerupDistribution;
          is_published?: boolean;
          is_featured?: boolean;
          play_count?: number;
          likes?: number;
          dislikes?: number;
          average_rating?: number;
          version?: number;
        };
      };
      games: {
        Row: {
          id: string;
          room_code: string | null;
          host_id: string | null;
          status: GameStatus;
          map_id: string | null;
          settings: GameSettings;
          winner_id: string | null;
          rounds_played: number;
          game_type: GameType;
          tournament_id: string | null;
          tournament_round: number | null;
          tournament_match: number | null;
          server_region: string | null;
          server_id: string | null;
          created_at: string;
          started_at: string | null;
          finished_at: string | null;
        };
        Insert: {
          id?: string;
          room_code?: string | null;
          host_id?: string | null;
          status?: GameStatus;
          map_id?: string | null;
          settings?: GameSettings;
          game_type?: GameType;
          tournament_id?: string | null;
          tournament_round?: number | null;
          tournament_match?: number | null;
          server_region?: string | null;
          server_id?: string | null;
        };
        Update: {
          room_code?: string | null;
          host_id?: string | null;
          status?: GameStatus;
          map_id?: string | null;
          settings?: GameSettings;
          winner_id?: string | null;
          rounds_played?: number;
          game_type?: GameType;
          server_region?: string | null;
          server_id?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
        };
      };
      game_players: {
        Row: {
          id: string;
          game_id: string;
          player_id: string;
          slot_number: number;
          character_color: number;
          team_id: number | null;
          is_ready: boolean;
          is_spectator: boolean;
          connection_status: ConnectionStatus;
          kills: number;
          deaths: number;
          self_destructs: number;
          bombs_placed: number;
          powerups_collected: number;
          blocks_destroyed: number;
          damage_dealt: number;
          rounds_won: number;
          rounds_survived: number;
          placement: number | null;
          elo_before: number | null;
          elo_after: number | null;
          elo_change: number;
          joined_at: string;
          left_at: string | null;
        };
        Insert: {
          id?: string;
          game_id: string;
          player_id: string;
          slot_number: number;
          character_color?: number;
          team_id?: number | null;
          is_ready?: boolean;
          is_spectator?: boolean;
          connection_status?: ConnectionStatus;
        };
        Update: {
          slot_number?: number;
          character_color?: number;
          team_id?: number | null;
          is_ready?: boolean;
          is_spectator?: boolean;
          connection_status?: ConnectionStatus;
          kills?: number;
          deaths?: number;
          self_destructs?: number;
          bombs_placed?: number;
          powerups_collected?: number;
          blocks_destroyed?: number;
          damage_dealt?: number;
          rounds_won?: number;
          rounds_survived?: number;
          placement?: number | null;
          elo_before?: number | null;
          elo_after?: number | null;
          elo_change?: number;
          left_at?: string | null;
        };
      };
      achievements: {
        Row: {
          id: string;
          code: string;
          category: AchievementCategory;
          name: string;
          description: string;
          icon: string;
          rarity: AchievementRarity;
          points: number;
          criteria: AchievementCriteria;
          is_hidden: boolean;
          is_repeatable: boolean;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          category: AchievementCategory;
          name: string;
          description: string;
          icon: string;
          rarity?: AchievementRarity;
          points?: number;
          criteria: AchievementCriteria;
          is_hidden?: boolean;
          is_repeatable?: boolean;
          is_active?: boolean;
          sort_order?: number;
        };
        Update: {
          code?: string;
          category?: AchievementCategory;
          name?: string;
          description?: string;
          icon?: string;
          rarity?: AchievementRarity;
          points?: number;
          criteria?: AchievementCriteria;
          is_hidden?: boolean;
          is_repeatable?: boolean;
          is_active?: boolean;
          sort_order?: number;
        };
      };
      player_achievements: {
        Row: {
          id: string;
          player_id: string;
          achievement_id: string;
          progress: number;
          progress_max: number;
          unlocked_at: string | null;
          game_id: string | null;
          unlock_count: number;
          is_notified: boolean;
        };
        Insert: {
          id?: string;
          player_id: string;
          achievement_id: string;
          progress?: number;
          progress_max?: number;
          unlocked_at?: string | null;
          game_id?: string | null;
          unlock_count?: number;
          is_notified?: boolean;
        };
        Update: {
          progress?: number;
          progress_max?: number;
          unlocked_at?: string | null;
          unlock_count?: number;
          is_notified?: boolean;
        };
      };
      replays: {
        Row: {
          id: string;
          game_id: string;
          title: string | null;
          description: string | null;
          thumbnail_url: string | null;
          data: string | null;
          data_url: string | null;
          format_version: number;
          duration_seconds: number;
          tick_count: number;
          player_count: number;
          file_size_bytes: number | null;
          is_public: boolean;
          is_featured: boolean;
          view_count: number;
          download_count: number;
          likes: number;
          highlights: ReplayHighlight[];
          created_at: string;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          game_id: string;
          title?: string | null;
          description?: string | null;
          thumbnail_url?: string | null;
          data?: string | null;
          data_url?: string | null;
          format_version?: number;
          duration_seconds: number;
          tick_count: number;
          player_count: number;
          file_size_bytes?: number | null;
          is_public?: boolean;
          is_featured?: boolean;
          highlights?: ReplayHighlight[];
          expires_at?: string | null;
        };
        Update: {
          title?: string | null;
          description?: string | null;
          thumbnail_url?: string | null;
          data_url?: string | null;
          is_public?: boolean;
          is_featured?: boolean;
          view_count?: number;
          download_count?: number;
          likes?: number;
          highlights?: ReplayHighlight[];
          expires_at?: string | null;
        };
      };
      tournaments: {
        Row: {
          id: string;
          creator_id: string | null;
          name: string;
          description: string | null;
          banner_url: string | null;
          status: TournamentStatus;
          format: TournamentFormat;
          game_settings: GameSettings;
          map_pool: string[];
          min_players: number;
          max_players: number;
          current_players: number;
          prize_pool: TournamentPrizePool;
          entry_fee: number;
          bracket_data: TournamentBracket | null;
          current_round: number;
          total_rounds: number | null;
          rules_text: string | null;
          check_in_required: boolean;
          check_in_duration_minutes: number;
          registration_opens_at: string | null;
          registration_closes_at: string | null;
          starts_at: string | null;
          check_in_opens_at: string | null;
          finished_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          creator_id?: string | null;
          name: string;
          description?: string | null;
          banner_url?: string | null;
          status?: TournamentStatus;
          format: TournamentFormat;
          game_settings?: GameSettings;
          map_pool?: string[];
          min_players?: number;
          max_players: number;
          prize_pool?: TournamentPrizePool;
          entry_fee?: number;
          rules_text?: string | null;
          check_in_required?: boolean;
          check_in_duration_minutes?: number;
          registration_opens_at?: string | null;
          registration_closes_at?: string | null;
          starts_at?: string | null;
          check_in_opens_at?: string | null;
        };
        Update: {
          name?: string;
          description?: string | null;
          banner_url?: string | null;
          status?: TournamentStatus;
          game_settings?: GameSettings;
          map_pool?: string[];
          min_players?: number;
          max_players?: number;
          current_players?: number;
          prize_pool?: TournamentPrizePool;
          entry_fee?: number;
          bracket_data?: TournamentBracket | null;
          current_round?: number;
          total_rounds?: number | null;
          rules_text?: string | null;
          check_in_required?: boolean;
          check_in_duration_minutes?: number;
          registration_opens_at?: string | null;
          registration_closes_at?: string | null;
          starts_at?: string | null;
          check_in_opens_at?: string | null;
          finished_at?: string | null;
        };
      };
      tournament_participants: {
        Row: {
          id: string;
          tournament_id: string;
          player_id: string;
          seed: number | null;
          registered_at: string;
          checked_in_at: string | null;
          status: TournamentParticipantStatus;
          final_placement: number | null;
          wins: number;
          losses: number;
          games_played: number;
          bracket_position: string | null;
        };
        Insert: {
          id?: string;
          tournament_id: string;
          player_id: string;
          seed?: number | null;
          status?: TournamentParticipantStatus;
        };
        Update: {
          seed?: number | null;
          checked_in_at?: string | null;
          status?: TournamentParticipantStatus;
          final_placement?: number | null;
          wins?: number;
          losses?: number;
          games_played?: number;
          bracket_position?: string | null;
        };
      };
      friendships: {
        Row: {
          id: string;
          requester_id: string;
          addressee_id: string;
          status: FriendshipStatus;
          message: string | null;
          created_at: string;
          updated_at: string;
          accepted_at: string | null;
        };
        Insert: {
          id?: string;
          requester_id: string;
          addressee_id: string;
          status?: FriendshipStatus;
          message?: string | null;
        };
        Update: {
          status?: FriendshipStatus;
          message?: string | null;
          accepted_at?: string | null;
        };
      };
      chat_messages: {
        Row: {
          id: string;
          game_id: string | null;
          tournament_id: string | null;
          recipient_id: string | null;
          sender_id: string;
          content: string;
          message_type: ChatMessageType;
          metadata: Json;
          is_deleted: boolean;
          deleted_by: string | null;
          deleted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          game_id?: string | null;
          tournament_id?: string | null;
          recipient_id?: string | null;
          sender_id: string;
          content: string;
          message_type?: ChatMessageType;
          metadata?: Json;
        };
        Update: {
          is_deleted?: boolean;
          deleted_by?: string | null;
          deleted_at?: string | null;
        };
      };
      map_ratings: {
        Row: {
          id: string;
          map_id: string;
          player_id: string;
          rating: number;
          review: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          map_id: string;
          player_id: string;
          rating: number;
          review?: string | null;
        };
        Update: {
          rating?: number;
          review?: string | null;
        };
      };
      map_favorites: {
        Row: {
          id: string;
          map_id: string;
          player_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          map_id: string;
          player_id: string;
        };
        Update: never;
      };
      player_reports: {
        Row: {
          id: string;
          reporter_id: string;
          reported_id: string;
          game_id: string | null;
          reason: ReportReason;
          description: string | null;
          evidence_urls: string[];
          status: ReportStatus;
          reviewed_by: string | null;
          reviewed_at: string | null;
          action_taken: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          reporter_id: string;
          reported_id: string;
          game_id?: string | null;
          reason: ReportReason;
          description?: string | null;
          evidence_urls?: string[];
        };
        Update: {
          status?: ReportStatus;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          action_taken?: string | null;
        };
      };
      notifications: {
        Row: {
          id: string;
          player_id: string;
          type: NotificationType;
          title: string;
          body: string;
          action_url: string | null;
          action_data: Json;
          is_read: boolean;
          read_at: string | null;
          created_at: string;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          player_id: string;
          type: NotificationType;
          title: string;
          body: string;
          action_url?: string | null;
          action_data?: Json;
        };
        Update: {
          is_read?: boolean;
          read_at?: string | null;
        };
      };
      matchmaking_queue: {
        Row: {
          id: string;
          player_id: string;
          game_type: 'casual' | 'ranked';
          region_preferences: string[];
          elo_rating: number;
          elo_range_min: number | null;
          elo_range_max: number | null;
          party_id: string | null;
          party_leader: boolean;
          status: MatchmakingStatus;
          queued_at: string;
          expanded_at: string | null;
          matched_at: string | null;
        };
        Insert: {
          id?: string;
          player_id: string;
          game_type?: 'casual' | 'ranked';
          region_preferences?: string[];
          elo_rating: number;
          elo_range_min?: number | null;
          elo_range_max?: number | null;
          party_id?: string | null;
          party_leader?: boolean;
        };
        Update: {
          game_type?: 'casual' | 'ranked';
          region_preferences?: string[];
          elo_range_min?: number | null;
          elo_range_max?: number | null;
          status?: MatchmakingStatus;
          expanded_at?: string | null;
          matched_at?: string | null;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      update_elo: {
        Args: { winner_uuid: string; loser_uuid: string; is_ranked?: boolean };
        Returns: {
          winner_new_elo: number;
          winner_elo_change: number;
          loser_new_elo: number;
          loser_elo_change: number;
        };
      };
      update_elo_multiplayer: {
        Args: { game_uuid: string };
        Returns: void;
      };
      get_leaderboard: {
        Args: {
          p_limit?: number;
          p_offset?: number;
          p_time_filter?: string;
          p_sort_by?: string;
        };
        Returns: Array<{
          rank: number;
          player_id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          elo_rating: number;
          rank_tier: RankTier;
          total_wins: number;
          total_games: number;
          total_kills: number;
          win_rate: number;
          country_code: string | null;
        }>;
      };
      get_player_rank: {
        Args: { player_uuid: string };
        Returns: {
          global_rank: number;
          tier_rank: number;
          percentile: number;
        };
      };
      create_game_room: {
        Args: { host_uuid: string; p_settings?: Json };
        Returns: { game_id: string; room_code: string };
      };
      join_game_by_code: {
        Args: { p_room_code: string; player_uuid: string };
        Returns: { success: boolean; game_id: string | null; message: string };
      };
      finalize_game: {
        Args: { game_uuid: string; winner_uuid?: string };
        Returns: void;
      };
      check_achievements: {
        Args: { player_uuid: string; game_uuid?: string };
        Returns: Array<{
          achievement_id: string;
          achievement_code: string;
          achievement_name: string;
        }>;
      };
      send_notification: {
        Args: {
          p_player_id: string;
          p_type: NotificationType;
          p_title: string;
          p_body: string;
          p_action_url?: string;
          p_action_data?: Json;
        };
        Returns: string;
      };
      get_friend_suggestions: {
        Args: { player_uuid: string; p_limit?: number };
        Returns: Array<{
          suggested_id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          elo_rating: number;
          common_games: number;
        }>;
      };
      match_players: {
        Args: { player_ids: string[] };
        Returns: string;
      };
      generate_tournament_bracket: {
        Args: { tournament_uuid: string };
        Returns: TournamentBracket;
      };
    };
    Enums: {
      game_status: GameStatus;
      game_type: GameType;
      rank_tier: RankTier;
      achievement_rarity: AchievementRarity;
      achievement_category: AchievementCategory;
      tournament_status: TournamentStatus;
      tournament_format: TournamentFormat;
      tournament_participant_status: TournamentParticipantStatus;
      friendship_status: FriendshipStatus;
      chat_message_type: ChatMessageType;
      connection_status: ConnectionStatus;
      notification_type: NotificationType;
      report_reason: ReportReason;
      report_status: ReportStatus;
      matchmaking_status: MatchmakingStatus;
    };
  };
}

// ============================================================================
// HELPER TYPES
// ============================================================================

/** Extract row type from a table */
export type TableRow<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

/** Extract insert type from a table */
export type TableInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

/** Extract update type from a table */
export type TableUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

// Convenience type aliases
export type Profile = TableRow<'profiles'>;
export type ProfileInsert = TableInsert<'profiles'>;
export type ProfileUpdate = TableUpdate<'profiles'>;

export type Game = TableRow<'games'>;
export type GameInsert = TableInsert<'games'>;
export type GameUpdate = TableUpdate<'games'>;

export type GamePlayer = TableRow<'game_players'>;
export type GamePlayerInsert = TableInsert<'game_players'>;
export type GamePlayerUpdate = TableUpdate<'game_players'>;

export type GameMap = TableRow<'maps'>;
export type GameMapInsert = TableInsert<'maps'>;
export type GameMapUpdate = TableUpdate<'maps'>;

export type Achievement = TableRow<'achievements'>;
export type AchievementInsert = TableInsert<'achievements'>;

export type PlayerAchievement = TableRow<'player_achievements'>;
export type PlayerAchievementInsert = TableInsert<'player_achievements'>;

export type Replay = TableRow<'replays'>;
export type ReplayInsert = TableInsert<'replays'>;
export type ReplayUpdate = TableUpdate<'replays'>;

export type Tournament = TableRow<'tournaments'>;
export type TournamentInsert = TableInsert<'tournaments'>;
export type TournamentUpdate = TableUpdate<'tournaments'>;

export type TournamentParticipant = TableRow<'tournament_participants'>;
export type TournamentParticipantInsert = TableInsert<'tournament_participants'>;
export type TournamentParticipantUpdate = TableUpdate<'tournament_participants'>;

export type Friendship = TableRow<'friendships'>;
export type FriendshipInsert = TableInsert<'friendships'>;
export type FriendshipUpdate = TableUpdate<'friendships'>;

export type ChatMessage = TableRow<'chat_messages'>;
export type ChatMessageInsert = TableInsert<'chat_messages'>;

export type MapRating = TableRow<'map_ratings'>;
export type MapRatingInsert = TableInsert<'map_ratings'>;

export type MapFavorite = TableRow<'map_favorites'>;
export type Notification = TableRow<'notifications'>;
export type MatchmakingEntry = TableRow<'matchmaking_queue'>;

// With relations types (for joined queries)
export interface ProfileWithStats extends Profile {
  kd_ratio: number;
  win_rate: number;
}

export interface GameWithPlayers extends Game {
  players: (GamePlayer & { profile: Profile })[];
  map?: GameMap;
  winner?: Profile;
}

export interface AchievementWithProgress extends Achievement {
  player_achievement?: PlayerAchievement;
}

export interface FriendWithProfile extends Friendship {
  friend_profile: Profile;
}

export interface LeaderboardEntry {
  rank: number;
  player_id: string;
  username: string;
  display_name: string | null;
  avatar_url: string | null;
  elo_rating: number;
  rank_tier: RankTier;
  total_wins: number;
  total_games: number;
  total_kills: number;
  win_rate: number;
  country_code: string | null;
}
